language: csharp
dist: xenial
#sudo: required
mono: none
dotnet: 3.1
branches:
    only:
        - master
        - develop
before_script:
    - chmod -R a+x scripts
#script:
#    - dotnet restore
#    - dotnet build
#after_success:
scripts:
    - ./scripts/travis-success.sh
notifications:
    email:
        on_success: never
        on_failure: always